version: '3.6'
services:

  bot:
    image: napstr/baymax:master
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
#    ports:
#      - 127.0.0.1:8849:8849   # JProfiler
    volumes:
      - ./baymax.yaml:/opt/baymax/baymax.yaml:ro
      - ./models:/opt/baymax/models:ro
      - ./logs:/opt/baymax/logs
      - ./logs/gc:/opt/baymax/logs/gc
      - ./baymax.sqlite:/opt/baymax/baymax.sqlite
    stop_grace_period: 60s
    entrypoint:
      - java
# Common JVM Options:
      - -Xms256m
      - -Xmx256m
      - -XX:HeapDumpPath=emergencydump.hprof
# Hotspot Options:
      #- -XX:+HeapDumpOnOutOfMemoryError
      #- -Xlog:gc*:logs/gc/gc-%t.log::filesize=1g
      #- -XX:+UseG1GC
      #- -XX:+ParallelRefProcEnabled
      #- -XX:+UseStringDeduplication
# Open J9 Options:
      - -XX:+HeapDumpOnOutOfMemory
      - -Xgcpolicy:balanced
      - -Xverbosegclog:logs/gc/gc-%Y-%m-%d_%H-%M-%S.xml
# The Jar
      - -jar
      - baymax.jar

  #watchtower:
  #  image: v2tec/watchtower
  #  image: napstr/watchtower:arm64v8-latest
  #  restart: always
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --cleanup --label-enable --interval 300 #seconds
